version: '3'
services:
  app:
    build: .
    container_name: php_app
    ports:
    - "80:80"
    depends_on:
    - database
    volumes: 
      - ./php:/var/www/html
    restart: always
    networks:
      app-net:
        ipv4_address: 172.20.0.3

  database:
    image: mysql:5.5
    networks:
      app-net:
        ipv4_address: 172.20.0.4
    volumes: 
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment: 
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_USER: app
        MYSQL_PASSWORD: userpassword
        MYSQL_DATABASE: app
networks:
  app-net:
    ipam:
      config:
        - subnet: 172.20.0.0/24